import type { Metadata } from "next";
import "./globals.css";
import { poppins, protestStrike } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Tensr",
  description: "Generated by tensr.co",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${protestStrike.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

